DROP DATABASE IF EXISTS Produits;

CREATE DATABASE Produits CHARACTER SET 'utf8';
USE Produits;

CREATE TABLE Livre (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
titre VARCHAR(100),
prix FLOAT(6, 2),
url VARCHAR(400),
PRIMARY KEY(id)
)
ENGINE=INNODB;