DROP DATABASE IF EXISTS Produits;

CREATE DATABASE Produits CHARACTER SET 'utf8';
USE Produits;

CREATE TABLE Livre (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
titre TEXT,
prix FLOAT(6, 2),
url VARCHAR TEXT
site VARCHAR(50),
ean VARCHAR(100),
PRIMARY KEY(id)
)
ENGINE=INNODB;